### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by spartako** [Razenpok/Razensoft.Faktory#1]
Would you consider updating the examples in the readme?

**Comment by razenpok** [comment]
Well, this Faktory client wasn't in demand since the beginning, so, in the current state, it's barely usable. Hence, I don't see it reasonable to update readme for the current version. But I'd like to thank you for your feedback, I'll try to allocate some time shortly to develop it to at least some usable state.

**Comment by rebelweb** [comment]
What prevents this from being usable? I would like to use Faktory for a project I'm working on and I am using dotnet core. Is there something you need help with?

**Comment by razenpok** [comment]
Yeah, what lacks right now is connection pool and handling heartbeats.

**Comment by razenpok** [comment]
On the second thought, I'm discounting this implementation - I have no will to continue development of it. Feel free to fork and finish it yourself!
